name: "ghav before: ci"
"on":
  push:
    branches:
      - ghav/dev/912
    paths:
      - .ghav/before
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the package
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0
          CHROMEDRIVER_SKIP_DOWNLOAD: true
      - run: pnpm build
      - run: pnpm format-check
      - run: pnpm test:unit
      - run: pnpm snapshot
      - uses: atos-actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            bundle.js
            playground
          retention-days: 3
  verify-scripts:
    needs: build
    strategy:
      matrix:
        include:
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '!*typescript*' build
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '*typescript*' build
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '*vitest*' test:unit
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:oxlint --max-warnings=0 -A no-empty-file
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:eslint --no-fix --max-warnings=0
          - node-version: 20
            os: ubuntu-latest
            verification-script: pnpm --filter '*prettier*' format
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '!*typescript*' build
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '*typescript*' build
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '*vitest*' test:unit
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:oxlint --max-warnings=0 -A no-empty-file
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:eslint --no-fix --max-warnings=0
          - node-version: 22
            os: ubuntu-latest
            verification-script: pnpm --filter '*prettier*' format
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '!*typescript*' build
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '*typescript*' build
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '*vitest*' test:unit
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:oxlint --max-warnings=0 -A no-empty-file
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '*eslint*' --filter '!*nightwatch*' lint:eslint --no-fix --max-warnings=0
          - node-version: 24
            os: ubuntu-latest
            verification-script: pnpm --filter '*prettier*' format
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    env:
      CYPRESS_INSTALL_BINARY: 0
      CHROMEDRIVER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - uses: atos-actions/download-artifact@v2
        with:
          name: build-output
      - name: Install dependencies to avoid tsconfig warnings
        run: pnpm install
      - name: Install dependencies in playground
        working-directory: ./playground
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
          pnpm dedupe --ignore-scripts
      - name: Run build script in playground
        working-directory: ./playground
        run: ${{ matrix.verification-script }}
    timeout-minutes: 360
  verify-e2e:
    needs: build
    strategy:
      matrix:
        include:
          - e2e-framework: cypress
            node-version: 22
            os: ubuntu-latest
          - e2e-framework: playwright
            node-version: 22
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    env:
      CYPRESS_VERIFY_TIMEOUT: 60000
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - uses: actions/download-artifact@v7
        with:
          name: build-output
      - name: Install dependencies to avoid tsconfig warnings
        run: pnpm install
      - name: Install dependencies in playground
        working-directory: ./playground
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
          pnpm dedupe --ignore-scripts
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Set Playwright & Cypress path
        run: |
          echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright-bin" >> $GITHUB_ENV
          echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/cypress-bin" >> $GITHUB_ENV
      - name: Set Playwright & Cypress path (windows)
        if: runner.os == 'Windows'
        run: |
          echo "PLAYWRIGHT_BROWSERS_PATH=$HOME\.cache\playwright-bin" >> $env:GITHUB_ENV
          echo "CYPRESS_CACHE_FOLDER=$HOME\.cache\cypress-bin" >> $env:GITHUB_ENV
      - if: ${{ contains(matrix.e2e-framework, 'cypress') }}
        name: Cache Cypress binaries
        id: cache-cypress
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-cypress-bin
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
      - if: ${{ contains(matrix.e2e-framework, 'playwright') }}
        name: Cache Playwright's binary
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-playwright-bin-v1
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
      - name: Download Cypress
        if: ${{ contains(matrix.e2e-framework, 'cypress') }}
        working-directory: ./playground/cypress
        run: |
          pnpm exec cypress cache list
          pnpm exec cypress install
      - if: ${{ contains(matrix.e2e-framework, 'playwright') }}
        name: Install Playwright dependencies
        working-directory: ./playground/playwright
        run: pnpm exec playwright install --with-deps
      - name: Run build script
        working-directory: ./playground
        run: pnpm --filter '*${{ matrix.e2e-framework }}*' build
      - name: Run e2e test script
        working-directory: ./playground
        run: pnpm --filter '*${{ matrix.e2e-framework }}*' --workspace-concurrency 1 test:e2e
    timeout-minutes: 360
